steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/web:${REVISION_ID}', 'web/' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/app:${REVISION_ID}', 'app/' ]

  - name: 'gcr.io/google_containers/hyperkube:v1.5.3'
<<<<<<< HEAD
<<<<<<< HEAD
    env: ["KUBECONFIG=/workspace/prod-visa-gnib.kubeconfig"]
=======
    env: ["KUBECONFIG=/workspace/kubeconfig"]
>>>>>>> parent of d536c52... added create prod config shell script copied from kelseyhightower
=======
    env: ["KUBECONFIG=/workspace/kubeconfig"]
>>>>>>> parent of d536c52... added create prod config shell script copied from kelseyhightower
    entrypoint: '/hyperkube'
    args: ['kubectl','set', 'image', 'deployment/web-deployment', 'web=gcr.io/$PROJECT_ID/web:${REVISION_ID}']

  - name: 'gcr.io/google_containers/hyperkube:v1.5.3'
<<<<<<< HEAD
<<<<<<< HEAD
    env: ['KUBECONFIG=/workspace/prod-visa-gnib	.kubeconfig']
=======
    env: ['KUBECONFIG=/workspace/kubeconfig']
>>>>>>> parent of d536c52... added create prod config shell script copied from kelseyhightower
=======
    env: ['KUBECONFIG=/workspace/kubeconfig']
>>>>>>> parent of d536c52... added create prod config shell script copied from kelseyhightower
    entrypoint: '/hyperkube'
    args: ['kubectl','set', 'image', 'deployment/app-deployment', 'app=gcr.io/$PROJECT_ID/app:${REVISION_ID}']

  - name: 'gcr.io/google_containers/hyperkube:v1.5.3'
<<<<<<< HEAD
<<<<<<< HEAD
    env: ['KUBECONFIG=/workspace/prod-visa-gnib.kubeconfig']
=======
    env: ['KUBECONFIG=/workspace/kubeconfig']
>>>>>>> parent of d536c52... added create prod config shell script copied from kelseyhightower
=======
    env: ['KUBECONFIG=/workspace/kubeconfig']
>>>>>>> parent of d536c52... added create prod config shell script copied from kelseyhightower
    entrypoint: '/hyperkube'
    args: ['kubectl','apply', '-f', 'workspace/k8s-all-config.yaml']

images:
  - 'gcr.io/$PROJECT_ID/web:${REVISION_ID}'
  - 'gcr.io/$PROJECT_ID/app:${REVISION_ID}'