steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/web', 'web/' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/app', 'app/' ]

images:
  - 'gcr.io/$PROJECT_ID/web'
  - 'gcr.io/$PROJECT_ID/app'