# https://cloud.google.com/container-builder/docs/concepts/build-requests - values available in this context
steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/web:${TAG_NAME}', 'web/' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/app:${TAG_NAME}', 'app/' ]

  - name: 'gcr.io/google_containers/hyperkube:v1.5.3'
    env: ["KUBECONFIG=/workspace/kubeconfig"]
    entrypoint: '/hyperkube'
    args: ['kubectl','set', 'image', 'deployment/web-deployment', 'web=gcr.io/$PROJECT_ID/web:${TAG_NAME}']

#  - name: 'gcr.io/google_containers/hyperkube:v1.5.3'
#    env: ["KUBECONFIG=/workspace/kubeconfig"]
#    entrypoint: '/hyperkube'
#    args: ['kubectl','set', 'image', 'deployment/web-deployment', 'app=gcr.io/$PROJECT_ID/app:${TAG_NAME}']

  - name: 'gcr.io/google_containers/hyperkube:v1.5.3'
    env: ['KUBECONFIG=/workspace/kubeconfig']
    entrypoint: '/hyperkube'
    args: ['kubectl','apply', '-f', 'k8s-all-config.yaml']

images:
  - 'gcr.io/$PROJECT_ID/web:${TAG_NAME}'
  - 'gcr.io/$PROJECT_ID/app:${TAG_NAME}'