# https://cloud.google.com/container-builder/docs/concepts/build-requests - values available in this context
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/web:${TAG_NAME}', 'web/' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/web']
    id: 'image-push'

#  - name: 'gcr.io/cloud-builders/docker'
#    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/app:${TAG_NAME}', 'app/' ]
#
  - name: 'gcr.io/google_containers/hyperkube:v1.5.3'
    env: ["KUBECONFIG=/workspace/kubeconfig"]
    entrypoint: '/hyperkube'
    args: ['kubectl','set', 'image', 'deployment/web-deployment', 'web=gcr.io/$PROJECT_ID/web:${TAG_NAME}']
    id: 'deployment-conf-update'
    waitFor: ['image-push']

#  - name: 'gcr.io/google_containers/hyperkube:v1.5.3'
#    env: ["KUBECONFIG=/workspace/kubeconfig"]
#    entrypoint: '/hyperkube'
#    args: ['kubectl','set', 'image', 'deployment/app-deployment', 'app=gcr.io/$PROJECT_ID/app:${TAG_NAME}']

  - name: 'gcr.io/google_containers/hyperkube:v1.5.3'
    env: ['KUBECONFIG=/workspace/kubeconfig']
    entrypoint: '/hyperkube'
    args: ['kubectl','apply', '-f', 'k8s-all-config.yaml']
    waitFor: ['deployment-conf-update']