apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - name: web
        image: gcr.io/visa-gnib-notifier/visa-gnib-web:latest
        imagePullPolicy: Always
