apiVersion: v1
kind: ReplicationController
metadata:
  name: app-rc

spec:
  replicas: 1
  selector:
    name: app
    version: v0.3
  template:
    metadata:
      labels:
        name: app
        version: v0.3
    spec:
      containers:
      - name: app-container
        image: gcr.io/main-gcloud/visa-gnib-app:latest
        imagePullPolicy: Always
