apiVersion: v1
kind: ReplicationController
metadata:
  name: web-rc

spec:
  replicas: 2
  selector:
    name: web
    version: v0.2
  template:
    metadata:
      labels:
        name: web
        version: v0.2
    spec:
      containers:
      - name: web-rc
        image: gcr.io/visa-gnib-notifier/visa-gnib-web:latest
