apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: default
data:
  GCLOUD_PROJECT: visa-gnib-notifier
  MAILJET_API_KEY: e6e5fd4838b27c6e5cfe5324597b9a05
  MAILJET_SECRET_KEY: c91ca692e3cc27bd1093f5cd086e649f 
  MAILJET_SENDER: notification@visa-gnib.info